# Generated by Django 4.0.2 on 2022-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.CharField(choices=[(1, 'Patient'), (2, 'Doctor')], default=1, max_length=20),
        ),
    ]
