# Generated by Django 4.0.2 on 2022-09-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.CharField(choices=[('1', 'Patient'), ('1', 'Doctor')], default='1', max_length=20),
        ),
    ]
