# Generated by Django 4.0.2 on 2022-09-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_doctor_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.CharField(choices=[('1', 'Patient'), ('1', 'Doctor')], max_length=20),
        ),
    ]
